development:
  bucket: 'dev-cdn.artpocket.me'
  access_key_id: 'AKIAI4NDC7E4AMJZIP4A'
  secret_access_key: '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'
  s3_host_name: 's3-ap-northeast-1.amazonaws.com'

production:
  bucket: ENV['S3_BUCKET_NAME']
  access_key_id: ENV['S3_ACCESS_KEY_ID']
  secret_access_key: ENV['S3_SECRET_ACCESS_KEY']
  s3_host_name: ENV['S3_HOST_NAME']
